insert into categorie(libelle) values ('Epicerie');
insert into categorie(libelle) values ('Meubles');
insert into produit(description, libelle, promotion, prix, id_categorie) values ('sodas', 'coca', false, 5, 1);
insert into produit(description, libelle, promotion, prix, id_categorie) values ('sodas', 'orangina', false, 5, 1);
insert into produit(description, libelle, promotion, prix, id_categorie) values ('eau minérale',  'evian', false, 5,  1);
insert into produit(description, libelle, promotion, prix, id_categorie) values ('de salon', 'table', false, 200, 2);
insert into produit(description, libelle, promotion, prix, id_categorie) values ('de salon', 'chaise', false, 70,2);
insert into produit(description, libelle, promotion, prix, id_categorie) values ('de salon', 'canape', false, 1000,  2);
insert into produit(description, libelle, promotion, prix, id_categorie) values ('de salon', 'tapis', false, 100,  2);
insert into users(email, password, username) VALUES ('james@admin.com', '$2y$10$LEnr44C1Z38zuENUywsrHuIPM.6xR14lLx.9wxENh7BPvwRfR3HDi', 'James');
insert into roles(name) values ('ROLE_ADMIN');
insert into user_roles(user_id, role_id) VALUES (1, 1);
